### PR TITLE
[mce] Disable proximity sensor for x86.

### PR DESCRIPTION
**Pull request by locusf**

### CODE REVIEW

**Comment by thp** [comment]
What about x86 devices that have proximity sensors?

**Comment by locusf** [comment]
We will have to create separate configurations per device, I think this package should be renamed like nemo-configs-x86-vm

**Comment by thp** [comment]
CC'ing @saukko, as I can't merge this.

**Comment by locusf** [comment]
I can merge this, is it ok?

**Comment by thp** [comment]
LGTM from me, feel free to merge if nobody else opposes.

**Pull request merged**
